# Project Configuration
project:
  name: MyFirstCIProject
  version: 0.1.0
  description: My first JavaScript project to learn CI/CD practices

# Environment Settings
environment:
  language: javascript
  runtime: node
  version: 14.x

# Build Settings
build:
  package_manager: npm
  commands:
    - npm install

# Start Application
start:
  command: npm start
